//
//  Kana.swift
//  SimejiUITests
//
//  Created by Wayne on 2018/6/5.
//  Copyright © 2018年 Wayne. All rights reserved.
//

class Kana{
    
    static let KANA: Int = 1
    static let HIRAGANA: Int = 1
    static let KATAKANA: Int = 2
    
    static func isKana(fromText text: String) -> Bool{
        return ((Hiragana[text] != nil) || (Katakana[text] != nil)) ? true: false
    }
    
    static func isHiragana(fromText text: String) -> Bool{
        return Hiragana[text] != nil ? true: false
    }
    
    static func isKatakana(fromText text: String) -> Bool{
        return Katakana[text] != nil ? true: false
    }

    static let Hiragana = ["あ": ["key": "a", "class": KANA, "type": HIRAGANA],
                           "い": ["key": "i", "class": KANA, "type": HIRAGANA],
                           "う": ["key": "u", "class": KANA, "type": HIRAGANA],
                           "え": ["key": "e", "class": KANA, "type": HIRAGANA],
                           "お": ["key": "o", "class": KANA, "type": HIRAGANA],
                           "か": ["key": "ka", "class": KANA, "type": HIRAGANA],
                           "き": ["key": "ki", "class": KANA, "type": HIRAGANA],
                           "く": ["key": "ku", "class": KANA, "type": HIRAGANA],
                           "け": ["key": "ke", "class": KANA, "type": HIRAGANA],
                           "こ": ["key": "ko", "class": KANA, "type": HIRAGANA],
                           "さ": ["key": "sa", "class": KANA, "type": HIRAGANA],
                           "し": ["key": "shi", "class": KANA, "type": HIRAGANA],
                           "す": ["key": "su", "class": KANA, "type": HIRAGANA],
                           "せ": ["key": "se", "class": KANA, "type": HIRAGANA],
                           "そ": ["key": "so", "class": KANA, "type": HIRAGANA],
                           "た": ["key": "ta", "class": KANA, "type": HIRAGANA],
                           "ち": ["key": "chi", "class": KANA, "type": HIRAGANA],
                           "つ": ["key": "tsu", "class": KANA, "type": HIRAGANA],
                           "て": ["key": "te", "class": KANA, "type": HIRAGANA],
                           "と": ["key": "to", "class": KANA, "type": HIRAGANA],
                           "な": ["key": "na", "class": KANA, "type": HIRAGANA],
                           "に": ["key": "ni", "class": KANA, "type": HIRAGANA],
                           "ぬ": ["key": "nu", "class": KANA, "type": HIRAGANA],
                           "ね": ["key": "ne", "class": KANA, "type": HIRAGANA],
                           "の": ["key": "no", "class": KANA, "type": HIRAGANA],
                           "は": ["key": "ha", "class": KANA, "type": HIRAGANA],
                           "ひ": ["key": "hi", "class": KANA, "type": HIRAGANA],
                           "ふ": ["key": "fu", "class": KANA, "type": HIRAGANA],
                           "へ": ["key": "he", "class": KANA, "type": HIRAGANA],
                           "ほ": ["key": "ho", "class": KANA, "type": HIRAGANA],
                           "ま": ["key": "ma", "class": KANA, "type": HIRAGANA],
                           "み": ["key": "mi", "class": KANA, "type": HIRAGANA],
                           "む": ["key": "mu", "class": KANA, "type": HIRAGANA],
                           "め": ["key": "me", "class": KANA, "type": HIRAGANA],
                           "も": ["key": "mo", "class": KANA, "type": HIRAGANA],
                           "や": ["key": "ya", "class": KANA, "type": HIRAGANA],
                           "ゆ": ["key": "yu", "class": KANA, "type": HIRAGANA],
                           "よ": ["key": "yo", "class": KANA, "type": HIRAGANA],
                           "ら": ["key": "ra", "class": KANA, "type": HIRAGANA],
                           "り": ["key": "ri", "class": KANA, "type": HIRAGANA],
                           "る": ["key": "ru", "class": KANA, "type": HIRAGANA],
                           "れ": ["key": "re", "class": KANA, "type": HIRAGANA],
                           "ろ": ["key": "ro", "class": KANA, "type": HIRAGANA],
                           "わ": ["key": "wa", "class": KANA, "type": HIRAGANA],
                           "を": ["key": "wo", "class": KANA, "type": HIRAGANA],
                           "ん": ["key": "xn", "class": KANA, "type": HIRAGANA],
                           "が": ["key": "ga", "class": KANA, "type": HIRAGANA],
                           "ぎ": ["key": "gi", "class": KANA, "type": HIRAGANA],
                           "ぐ": ["key": "gu", "class": KANA, "type": HIRAGANA],
                           "げ": ["key": "ge", "class": KANA, "type": HIRAGANA],
                           "ご": ["key": "go", "class": KANA, "type": HIRAGANA],
                           "ざ": ["key": "za", "class": KANA, "type": HIRAGANA],
                           "じ": ["key": "ji", "class": KANA, "type": HIRAGANA],
                           "ず": ["key": "zu", "class": KANA, "type": HIRAGANA],
                           "ぜ": ["key": "ze", "class": KANA, "type": HIRAGANA],
                           "ぞ": ["key": "zo", "class": KANA, "type": HIRAGANA],
                           "だ": ["key": "da", "class": KANA, "type": HIRAGANA],
                           "ぢ": ["key": "di", "class": KANA, "type": HIRAGANA],
                           "づ": ["key": "du", "class": KANA, "type": HIRAGANA],
                           "で": ["key": "de", "class": KANA, "type": HIRAGANA],
                           "ど": ["key": "do", "class": KANA, "type": HIRAGANA],
                           "ば": ["key": "ba", "class": KANA, "type": HIRAGANA],
                           "び": ["key": "bi", "class": KANA, "type": HIRAGANA],
                           "ぶ": ["key": "bu", "class": KANA, "type": HIRAGANA],
                           "べ": ["key": "be", "class": KANA, "type": HIRAGANA],
                           "ぼ": ["key": "bo", "class": KANA, "type": HIRAGANA],
                           "ぱ": ["key": "pa", "class": KANA, "type": HIRAGANA],
                           "ぴ": ["key": "pi", "class": KANA, "type": HIRAGANA],
                           "ぷ": ["key": "pu", "class": KANA, "type": HIRAGANA],
                           "ぺ": ["key": "pe", "class": KANA, "type": HIRAGANA],
                           "ぽ": ["key": "po", "class": KANA, "type": HIRAGANA],
                           "ー": ["key": "ー", "class": KANA, "type": HIRAGANA],
                           "ぁ": ["key": "xa", "class": KANA, "type": HIRAGANA],
                           "ぃ": ["key": "xi", "class": KANA, "type": HIRAGANA],
                           "ぅ": ["key": "xu", "class": KANA, "type": HIRAGANA],
                           "ぇ": ["key": "xe", "class": KANA, "type": HIRAGANA],
                           "ぉ": ["key": "xo", "class": KANA, "type": HIRAGANA],
                           "っ": ["key": "xtu", "class": KANA, "type": HIRAGANA],
                           "ゎ": ["key": "xwa", "class": KANA, "type": HIRAGANA],
                           "ゃ": ["key": "xya", "class": KANA, "type": HIRAGANA],
                           "ゅ": ["key": "xyu", "class": KANA, "type": HIRAGANA],
                           "ょ": ["key": "xyo", "class": KANA, "type": HIRAGANA]]
    
    static let Katakana = ["ア": ["key": "a", "class": KANA, "type": KATAKANA],
                           "イ": ["key": "i", "class": KANA, "type": KATAKANA],
                           "ウ": ["key": "u", "class": KANA, "type": KATAKANA],
                           "エ": ["key": "e", "class": KANA, "type": KATAKANA],
                           "オ": ["key": "o", "class": KANA, "type": KATAKANA],
                           "カ": ["key": "ka", "class": KANA, "type": KATAKANA],
                           "キ": ["key": "ki", "class": KANA, "type": KATAKANA],
                           "ク": ["key": "ku", "class": KANA, "type": KATAKANA],
                           "ケ": ["key": "ke", "class": KANA, "type": KATAKANA],
                           "コ": ["key": "ko", "class": KANA, "type": KATAKANA],
                           "サ": ["key": "sa", "class": KANA, "type": KATAKANA],
                           "シ": ["key": "shi", "class": KANA, "type": KATAKANA],
                           "ス": ["key": "su", "class": KANA, "type": KATAKANA],
                           "セ": ["key": "se", "class": KANA, "type": KATAKANA],
                           "ソ": ["key": "so", "class": KANA, "type": KATAKANA],
                           "タ": ["key": "ta", "class": KANA, "type": KATAKANA],
                           "チ": ["key": "chi", "class": KANA, "type": KATAKANA],
                           "ツ": ["key": "tsu", "class": KANA, "type": KATAKANA],
                           "テ": ["key": "te", "class": KANA, "type": KATAKANA],
                           "ト": ["key": "to", "class": KANA, "type": KATAKANA],
                           "ナ": ["key": "na", "class": KANA, "type": KATAKANA],
                           "ニ": ["key": "ni", "class": KANA, "type": KATAKANA],
                           "ヌ": ["key": "nu", "class": KANA, "type": KATAKANA],
                           "ネ": ["key": "ne", "class": KANA, "type": KATAKANA],
                           "ノ": ["key": "no", "class": KANA, "type": KATAKANA],
                           "ハ": ["key": "ha", "class": KANA, "type": KATAKANA],
                           "ヒ": ["key": "hi", "class": KANA, "type": KATAKANA],
                           "フ": ["key": "fu", "class": KANA, "type": KATAKANA],
                           "ヘ": ["key": "he", "class": KANA, "type": KATAKANA],
                           "ホ": ["key": "ho", "class": KANA, "type": KATAKANA],
                           "ヤ": ["key": "ya", "class": KANA, "type": KATAKANA],
                           "ユ": ["key": "yu", "class": KANA, "type": KATAKANA],
                           "ヨ": ["key": "yo", "class": KANA, "type": KATAKANA],
                           "ラ": ["key": "ra", "class": KANA, "type": KATAKANA],
                           "リ": ["key": "ri", "class": KANA, "type": KATAKANA],
                           "ル": ["key": "ru", "class": KANA, "type": KATAKANA],
                           "レ": ["key": "re", "class": KANA, "type": KATAKANA],
                           "ロ": ["key": "ro", "class": KANA, "type": KATAKANA],
                           "ワ": ["key": "wa", "class": KANA, "type": KATAKANA],
                           "ヲ": ["key": "wo", "class": KANA, "type": KATAKANA],
                           "ン": ["key": "ru", "class": KANA, "type": KATAKANA],
                           "ガ": ["key": "ga", "class": KANA, "type": KATAKANA],
                           "ギ": ["key": "gi", "class": KANA, "type": KATAKANA],
                           "グ": ["key": "gu", "class": KANA, "type": KATAKANA],
                           "ゲ": ["key": "ge", "class": KANA, "type": KATAKANA],
                           "ゴ": ["key": "go", "class": KANA, "type": KATAKANA],
                           "ザ": ["key": "za", "class": KANA, "type": KATAKANA],
                           "ジ": ["key": "ji", "class": KANA, "type": KATAKANA],
                           "ズ": ["key": "zu", "class": KANA, "type": KATAKANA],
                           "ゼ": ["key": "ze", "class": KANA, "type": KATAKANA],
                           "ゾ": ["key": "zo", "class": KANA, "type": KATAKANA],
                           "ダ": ["key": "da", "class": KANA, "type": KATAKANA],
                           "ヂ": ["key": "dji", "class": KANA, "type": KATAKANA],
                           "ヅ": ["key": "dzu", "class": KANA, "type": KATAKANA],
                           "デ": ["key": "de", "class": KANA, "type": KATAKANA],
                           "ド": ["key": "do", "class": KANA, "type": KATAKANA],
                           "バ": ["key": "ba", "class": KANA, "type": KATAKANA],
                           "ビ": ["key": "bi", "class": KANA, "type": KATAKANA],
                           "ブ": ["key": "bu", "class": KANA, "type": KATAKANA],
                           "ベ": ["key": "be", "class": KANA, "type": KATAKANA],
                           "ボ": ["key": "bo", "class": KANA, "type": KATAKANA],
                           "パ": ["key": "pa", "class": KANA, "type": KATAKANA],
                           "ピ": ["key": "pi", "class": KANA, "type": KATAKANA],
                           "プ": ["key": "pu", "class": KANA, "type": KATAKANA],
                           "ペ": ["key": "pe", "class": KANA, "type": KATAKANA],
                           "ポ": ["key": "po", "class": KANA, "type": KATAKANA],
                           "ャ": ["key": "xa", "class": KANA, "type": KATAKANA],
                           "ィ": ["key": "xi", "class": KANA, "type": KATAKANA],
                           "ゥ": ["key": "xu", "class": KANA, "type": KATAKANA],
                           "ェ": ["key": "xe", "class": KANA, "type": KATAKANA],
                           "ォ": ["key": "xo", "class": KANA, "type": KATAKANA],
                           "ッ": ["key": "xtu", "class": KANA, "type": KATAKANA],
                           "ヮ": ["key": "xwa", "class": KANA, "type": KATAKANA],
                           "ュ": ["key": "xyu", "class": KANA, "type": KATAKANA],
                           "ョ": ["key": "xyo", "class": KANA, "type": KATAKANA]]
    
}
